'use client';

import { useEffect, useState } from 'react';

type Report = {
  id: string;
  title: string;
  periodStart: string;
  periodEnd: string;
  generatedBy: string;
  createdAt: string;
  contentJson: string;
};

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [title, setTitle] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);

  useEffect(() => {
    load();
  }, []);

  async function load() {
    setLoading(true);
    try {
      const res = await fetch('/api/reports');
      if (res.ok) {
        const data: Report[] = await res.json();
        setReports(data);
        if (data.length > 0 && !selectedReport) {
          setSelectedReport(data[0]);
        }
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  }

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    if (!title.trim()) return;
    setGenerating(true);

    try {
      const res = await fetch('/api/reports', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title }),
      });

      if (res.ok) {
        setTitle('');
        setShowForm(false);
        await load();
      }
    } catch (e) {
      console.error(e);
    } finally {
      setGenerating(false);
    }
  }

  function handlePrint() {
    window.print();
  }

  function handleExportCSV() {
    if (!selectedReport) return;
    let data: any = {};
    try {
      data = JSON.parse(selectedReport.contentJson);
    } catch (e) {
      data = {};
    }

    const rows = [
      ['Report Property', 'Value'],
      ['Report Title', selectedReport.title],
      ['Generated By', selectedReport.generatedBy],
      ['Generated Date', new Date(selectedReport.createdAt).toLocaleString()],
      ['Executive Summary', `"${(data.summary || '').replace(/"/g, '""')}"`],
      ['Total Analyzed Feedbacks', data.totalAnalyzed || 0],
      ['Customer Satisfaction Score (CSAT)', `${data.csatScore || Math.round((data.positiveRatio || 0.7) * 100)}%`],
      ['Net Promoter Score (NPS Index)', data.npsIndex || 0],
      ['Positive Feedback Count', data.positiveCount || 0],
      ['Neutral Feedback Count', data.neutralCount || 0],
      ['Negative Feedback Count', data.negativeCount || 0],
      ['Support Tickets Count', data.channelBreakdown?.supportTickets || 0],
      ['App Store Reviews Count', data.channelBreakdown?.appStoreReviews || 0],
      ['NPS Surveys Count', data.channelBreakdown?.npsSurveys || 0],
      ['Sales Calls Count', data.channelBreakdown?.salesCalls || 0],
      ['Community Posts Count', data.channelBreakdown?.communityPosts || 0],
      ['Top Theme Clusters', `"${(data.topThemes || []).join(', ')}"`],
      ['Critical Pain Points', `"${(data.criticalPainPoints || []).join(' | ')}"`],
      ['Key Action Items', `"${(data.keyActionItems || []).join(' | ')}"`],
    ];

    if (Array.isArray(data.strategicRoadmap)) {
      rows.push(['Strategic Roadmap', '']);
      data.strategicRoadmap.forEach((item: any) => {
        rows.push([`[${item.priority}] ${item.initiative}`, `Impact: ${item.impact}`]);
      });
    }

    const csvContent = 'data:text/csv;charset=utf-8,' + rows.map((e) => e.join(',')).join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute(
      'download',
      `${selectedReport.title.replace(/\s+/g, '-').toLowerCase()}-${new Date(selectedReport.createdAt).toISOString().slice(0, 10)}.csv`
    );
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  function handleExportJSON() {
    if (!selectedReport) return;
    const blob = new Blob([selectedReport.contentJson], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${selectedReport.title.replace(/\s+/g, '-').toLowerCase()}-${new Date(selectedReport.createdAt).toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="p-6 md:p-8 max-w-7xl mx-auto w-full space-y-8 animate-fadeIn">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-white/10 pb-6 print:hidden">
        <div>
          <h1 className="text-2xl md:text-3xl font-extrabold text-white tracking-tight flex items-center gap-2">
            <span>Executive Feedback Reports</span>
          </h1>
          <p className="text-gray-400 text-sm mt-1">
            In-depth AI intelligence reports with embedded analytics charts, CSAT/NPS metrics, risk flags, and PDF exports.
          </p>
        </div>
        <button
          onClick={() => setShowForm(!showForm)}
          className="px-4 py-2.5 rounded-xl text-sm font-semibold bg-gradient-to-r from-indigo-500 to-purple-600 hover:opacity-90 text-white shadow-md shadow-indigo-500/20 transition-all cursor-pointer"
        >
          {showForm ? '✕ Close Form' : '✨ Generate AI Report'}
        </button>
      </div>

      {/* Generate Report Form */}
      {showForm && (
        <form onSubmit={handleGenerate} className="glass-panel p-6 space-y-4 border-indigo-500/40 animate-fadeIn print:hidden">
          <h3 className="text-base font-bold text-white">Generate Executive Summary</h3>
          <div>
            <label className="text-xs font-semibold text-gray-400 block mb-1">Report Title</label>
            <input
              type="text"
              placeholder="e.g. Q3 Comprehensive Customer Feedback Intelligence Report"
              className="glass-input w-full text-sm"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
            />
          </div>
          <div className="flex justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={() => setShowForm(false)}
              className="px-4 py-2 rounded-lg text-sm text-gray-400 hover:text-white"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={generating}
              className="px-5 py-2 rounded-lg text-sm font-semibold bg-indigo-600 hover:bg-indigo-500 text-white shadow-md shadow-indigo-500/20 disabled:opacity-50 cursor-pointer"
            >
              {generating ? 'Synthesizing Detailed Report...' : 'Generate Report'}
            </button>
          </div>
        </form>
      )}

      {/* Reports Split Layout */}
      {loading ? (
        <div className="text-center py-12 text-gray-400 text-sm">Loading executive reports...</div>
      ) : reports.length === 0 ? (
        <div className="glass-panel p-12 text-center text-gray-400 text-sm">
          No reports generated yet. Click &quot;Generate AI Report&quot; to synthesize your first comprehensive summary.
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Left Column: Report History List */}
          <div className="space-y-3 print:hidden">
            <h3 className="text-sm font-bold uppercase tracking-wider text-gray-400 px-1">Generated Reports</h3>
            {reports.map((report) => {
              const isSelected = selectedReport?.id === report.id;
              return (
                <button
                  key={report.id}
                  onClick={() => setSelectedReport(report)}
                  className={`w-full text-left p-4 rounded-xl transition-all border cursor-pointer ${
                    isSelected
                      ? 'bg-indigo-600/20 border-indigo-500/50 shadow-md shadow-indigo-500/10'
                      : 'glass-panel hover:border-white/20'
                  }`}
                >
                  <h4 className="text-sm font-bold text-white mb-1 line-clamp-1">{report.title}</h4>
                  <div className="flex items-center justify-between text-xs text-gray-400">
                    <span>By {report.generatedBy}</span>
                    <span className="font-mono">{new Date(report.createdAt).toLocaleDateString()}</span>
                  </div>
                </button>
              );
            })}
          </div>

          {/* Right Column: Selected Report Detailed Preview & Exports */}
          <div className="lg:col-span-2">
            {selectedReport && (
              <div className="glass-panel p-8 space-y-8 border-indigo-500/30 print:p-0 print:border-none print:shadow-none print:bg-white print:text-black">
                {/* Report Header & Action Buttons */}
                <div className="border-b border-white/10 print:border-black/20 pb-6 flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                  <div>
                    <h2 className="text-2xl font-extrabold text-white print:text-black">{selectedReport.title}</h2>
                    <p className="text-xs text-gray-400 print:text-gray-600 mt-1">
                      Generated by <strong className="text-indigo-300 print:text-indigo-700">{selectedReport.generatedBy}</strong> on{' '}
                      {new Date(selectedReport.createdAt).toLocaleString()}
                    </p>
                  </div>
                  <div className="flex flex-wrap items-center gap-2 print:hidden">
                    <button
                      onClick={handlePrint}
                      className="px-3.5 py-2 rounded-xl text-xs font-bold bg-gradient-to-r from-indigo-500 to-purple-600 hover:opacity-90 text-white shadow-md shadow-indigo-500/20 transition-all flex items-center gap-1.5 cursor-pointer"
                    >
                      <span>🖨️</span>
                      <span>Export PDF / Print Report</span>
                    </button>
                    <button
                      onClick={handleExportCSV}
                      className="px-3 py-1.5 rounded-lg text-xs font-semibold bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-300 border border-emerald-500/30 transition-all flex items-center gap-1 cursor-pointer"
                    >
                      <span>📊</span>
                      <span>Export CSV</span>
                    </button>
                    <button
                      onClick={handleExportJSON}
                      className="px-3 py-1.5 rounded-lg text-xs font-semibold bg-purple-500/20 hover:bg-purple-500/30 text-purple-300 border border-purple-500/30 transition-all flex items-center gap-1 cursor-pointer"
                    >
                      <span>⚙️</span>
                      <span>Export JSON</span>
                    </button>
                  </div>
                </div>

                {/* Parsed Detailed Content with Embedded Analytics Components */}
                {(() => {
                  try {
                    const data = JSON.parse(selectedReport.contentJson);
                    const csat = data.csatScore || Math.round((data.positiveRatio || 0.7) * 100);
                    const nps = data.npsIndex || 0;
                    const cb = data.channelBreakdown || {};
                    const totalAnalyzed = data.totalAnalyzed || 1;

                    const posCount = data.positiveCount || 0;
                    const neuCount = data.neutralCount || 0;
                    const negCount = data.negativeCount || 0;

                    const posPct = Math.round((posCount / totalAnalyzed) * 100);
                    const neuPct = Math.round((neuCount / totalAnalyzed) * 100);
                    const negPct = Math.round((negCount / totalAnalyzed) * 100);

                    // SVG Donut Chart Calculation for PDF Print output
                    const circumference = 2 * Math.PI * 40;
                    const posStroke = (posPct / 100) * circumference;
                    const neuStroke = (neuPct / 100) * circumference;
                    const negStroke = (negPct / 100) * circumference;

                    return (
                      <div className="space-y-8 text-sm text-gray-200 print:text-black">
                        {/* Executive Summary */}
                        <div>
                          <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-400 print:text-indigo-800 mb-2">
                            Executive Synthesis
                          </h3>
                          <p className="p-5 rounded-xl bg-slate-900/90 border border-white/10 print:bg-gray-100 print:border-gray-300 print:text-black leading-relaxed text-sm text-gray-100">
                            {data.summary}
                          </p>
                        </div>

                        {/* Embedded Analytics Section Header */}
                        <div className="pt-2 border-t border-white/10 print:border-gray-300">
                          <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-400 print:text-indigo-800 mb-4 flex items-center gap-2">
                            <span>📈 Embedded Feedback Analytics & CSAT Metrics</span>
                          </h3>

                          {/* Metrics Overview Grid */}
                          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-6">
                            <div className="p-4 rounded-xl bg-slate-900/80 border border-white/10 print:bg-gray-50 print:border-gray-300">
                              <span className="text-xs text-gray-400 print:text-gray-600 block">Total Analyzed</span>
                              <span className="text-2xl font-extrabold text-white print:text-black mt-1 block">
                                {data.totalAnalyzed || 0}
                              </span>
                            </div>
                            <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/20 print:bg-emerald-50 print:border-emerald-300">
                              <span className="text-xs text-emerald-400 print:text-emerald-800 block">CSAT Satisfaction</span>
                              <span className="text-2xl font-extrabold text-emerald-300 print:text-emerald-700 mt-1 block">
                                {csat}%
                              </span>
                            </div>
                            <div className="p-4 rounded-xl bg-indigo-500/10 border border-indigo-500/20 print:bg-indigo-50 print:border-indigo-300">
                              <span className="text-xs text-indigo-400 print:text-indigo-800 block">Net Promoter Index</span>
                              <span className="text-2xl font-extrabold text-indigo-300 print:text-indigo-700 mt-1 block">
                                +{nps}
                              </span>
                            </div>
                            <div className="p-4 rounded-xl bg-purple-500/10 border border-purple-500/20 print:bg-purple-50 print:border-purple-300">
                              <span className="text-xs text-purple-400 print:text-purple-800 block">Positive Ratio</span>
                              <span className="text-2xl font-extrabold text-purple-300 print:text-purple-700 mt-1 block">
                                {((data.positiveRatio || 0) * 100).toFixed(0)}%
                              </span>
                            </div>
                          </div>

                          {/* Analytics Donut Pie Chart & Breakdown */}
                          <div className="p-6 rounded-xl bg-slate-900/80 border border-white/10 print:bg-gray-50 print:border-gray-300 flex flex-col sm:flex-row items-center justify-between gap-6">
                            <div className="relative w-36 h-36 flex items-center justify-center">
                              <svg className="w-full h-full transform -rotate-90" viewBox="0 0 100 100">
                                <circle cx="50" cy="50" r="40" stroke="#1e293b" strokeWidth="16" fill="transparent" />
                                <circle
                                  cx="50"
                                  cy="50"
                                  r="40"
                                  stroke="#10b981"
                                  strokeWidth="16"
                                  fill="transparent"
                                  strokeDasharray={`${posStroke} ${circumference}`}
                                  strokeDashoffset="0"
                                />
                                <circle
                                  cx="50"
                                  cy="50"
                                  r="40"
                                  stroke="#f59e0b"
                                  strokeWidth="16"
                                  fill="transparent"
                                  strokeDasharray={`${neuStroke} ${circumference}`}
                                  strokeDashoffset={`-${posStroke}`}
                                />
                                <circle
                                  cx="50"
                                  cy="50"
                                  r="40"
                                  stroke="#f43f5e"
                                  strokeWidth="16"
                                  fill="transparent"
                                  strokeDasharray={`${negStroke} ${circumference}`}
                                  strokeDashoffset={`-${posStroke + neuStroke}`}
                                />
                              </svg>
                              <div className="absolute inset-0 flex flex-col items-center justify-center text-center">
                                <span className="text-xl font-extrabold text-white print:text-black">{csat}%</span>
                                <span className="text-[9px] text-emerald-400 print:text-emerald-700 font-bold">CSAT</span>
                              </div>
                            </div>

                            <div className="flex-1 space-y-2 w-full text-xs">
                              <div className="flex justify-between items-center p-2 rounded bg-emerald-500/10 print:bg-emerald-50 border border-emerald-500/20 print:border-emerald-300">
                                <span className="text-emerald-400 print:text-emerald-800 font-bold">Positive 🟢</span>
                                <span className="font-extrabold text-emerald-300 print:text-emerald-700">
                                  {posCount} ({posPct}%)
                                </span>
                              </div>
                              <div className="flex justify-between items-center p-2 rounded bg-amber-500/10 print:bg-amber-50 border border-amber-500/20 print:border-amber-300">
                                <span className="text-amber-400 print:text-amber-800 font-bold">Neutral 🟡</span>
                                <span className="font-extrabold text-amber-300 print:text-amber-700">
                                  {neuCount} ({neuPct}%)
                                </span>
                              </div>
                              <div className="flex justify-between items-center p-2 rounded bg-rose-500/10 print:bg-rose-50 border border-rose-500/20 print:border-rose-300">
                                <span className="text-rose-400 print:text-rose-800 font-bold">Negative 🔴</span>
                                <span className="font-extrabold text-rose-300 print:text-rose-700">
                                  {negCount} ({negPct}%)
                                </span>
                              </div>
                            </div>
                          </div>
                        </div>

                        {/* Channel Volume Breakdown Bars */}
                        <div className="p-5 rounded-xl bg-slate-900/80 border border-white/10 print:bg-gray-50 print:border-gray-300 space-y-3">
                          <h4 className="text-xs font-bold uppercase tracking-wider text-gray-400 print:text-gray-700">
                            Channel Volume Distribution
                          </h4>
                          <div className="grid grid-cols-2 sm:grid-cols-5 gap-2 text-xs">
                            <div className="p-2 rounded bg-white/5 print:bg-white print:border print:border-gray-200 text-center">
                              <span className="text-gray-400 print:text-gray-600 block text-[10px]">Support Tickets</span>
                              <span className="font-bold text-white print:text-black text-sm">{cb.supportTickets || 0}</span>
                            </div>
                            <div className="p-2 rounded bg-white/5 print:bg-white print:border print:border-gray-200 text-center">
                              <span className="text-gray-400 print:text-gray-600 block text-[10px]">App Store</span>
                              <span className="font-bold text-white print:text-black text-sm">{cb.appStoreReviews || 0}</span>
                            </div>
                            <div className="p-2 rounded bg-white/5 print:bg-white print:border print:border-gray-200 text-center">
                              <span className="text-gray-400 print:text-gray-600 block text-[10px]">NPS Surveys</span>
                              <span className="font-bold text-white print:text-black text-sm">{cb.npsSurveys || 0}</span>
                            </div>
                            <div className="p-2 rounded bg-white/5 print:bg-white print:border print:border-gray-200 text-center">
                              <span className="text-gray-400 print:text-gray-600 block text-[10px]">Sales Calls</span>
                              <span className="font-bold text-white print:text-black text-sm">{cb.salesCalls || 0}</span>
                            </div>
                            <div className="p-2 rounded bg-white/5 print:bg-white print:border print:border-gray-200 text-center">
                              <span className="text-gray-400 print:text-gray-600 block text-[10px]">Community</span>
                              <span className="font-bold text-white print:text-black text-sm">{cb.communityPosts || 0}</span>
                            </div>
                          </div>
                        </div>

                        {/* Top Themes */}
                        {data.topThemes && (
                          <div>
                            <h3 className="text-xs font-bold uppercase tracking-wider text-purple-400 print:text-purple-800 mb-3">
                              Top Theme Clusters
                            </h3>
                            <div className="flex flex-wrap gap-2">
                              {data.topThemes.map((t: string, idx: number) => (
                                <span
                                  key={idx}
                                  className="px-3.5 py-1.5 rounded-lg bg-purple-500/20 print:bg-purple-100 text-purple-300 print:text-purple-900 border border-purple-500/30 print:border-purple-300 text-xs font-semibold"
                                >
                                  #{idx + 1} {t}
                                </span>
                              ))}
                            </div>
                          </div>
                        )}

                        {/* Critical Pain Points & Churn Risks */}
                        {data.criticalPainPoints && (
                          <div>
                            <h3 className="text-xs font-bold uppercase tracking-wider text-rose-400 print:text-rose-800 mb-3 flex items-center gap-1.5">
                              <span>⚠️ Critical Pain Points & Churn Risks</span>
                            </h3>
                            <div className="space-y-2">
                              {data.criticalPainPoints.map((point: string, idx: number) => (
                                <div
                                  key={idx}
                                  className="p-3.5 rounded-xl bg-rose-500/10 print:bg-rose-50 border border-rose-500/20 print:border-rose-300 text-xs text-rose-200 print:text-rose-900 flex items-start gap-2"
                                >
                                  <span className="font-bold text-rose-400 print:text-rose-700">🚨</span>
                                  <span>{point}</span>
                                </div>
                              ))}
                            </div>
                          </div>
                        )}

                        {/* Recommended Action Items */}
                        {data.keyActionItems && (
                          <div>
                            <h3 className="text-xs font-bold uppercase tracking-wider text-amber-400 print:text-amber-800 mb-3">
                              Tactical Action Items
                            </h3>
                            <ul className="space-y-2">
                              {data.keyActionItems.map((item: string, idx: number) => (
                                <li
                                  key={idx}
                                  className="p-3.5 rounded-xl bg-slate-900/90 print:bg-gray-50 border border-white/10 print:border-gray-300 flex items-start gap-3 text-xs"
                                >
                                  <span className="px-2 py-0.5 rounded bg-amber-500/20 print:bg-amber-100 text-amber-300 print:text-amber-900 font-bold text-[10px]">
                                    STEP {idx + 1}
                                  </span>
                                  <span className="text-gray-200 print:text-black">{item}</span>
                                </li>
                              ))}
                            </ul>
                          </div>
                        )}

                        {/* Strategic C-Suite Roadmap */}
                        {data.strategicRoadmap && (
                          <div>
                            <h3 className="text-xs font-bold uppercase tracking-wider text-cyan-400 print:text-cyan-800 mb-3">
                              Strategic C-Suite Product Roadmap
                            </h3>
                            <div className="overflow-x-auto rounded-xl border border-white/10 print:border-gray-300">
                              <table className="w-full text-left text-xs">
                                <thead className="bg-slate-900/90 print:bg-gray-100 text-gray-400 print:text-gray-800 font-semibold border-b border-white/10 print:border-gray-300">
                                  <tr>
                                    <th className="p-3">Priority</th>
                                    <th className="p-3">Initiative</th>
                                    <th className="p-3">Target Impact</th>
                                  </tr>
                                </thead>
                                <tbody className="divide-y divide-white/5 print:divide-gray-200">
                                  {data.strategicRoadmap.map((item: any, idx: number) => (
                                    <tr key={idx} className="hover:bg-white/5 print:hover:bg-gray-50">
                                      <td className="p-3">
                                        <span
                                          className={`px-2 py-0.5 rounded font-bold text-[10px] ${
                                            item.priority === 'HIGH'
                                              ? 'bg-rose-500/20 print:bg-rose-100 text-rose-300 print:text-rose-900 border border-rose-500/30'
                                              : item.priority === 'MEDIUM'
                                              ? 'bg-amber-500/20 print:bg-amber-100 text-amber-300 print:text-amber-900 border border-amber-500/30'
                                              : 'bg-indigo-500/20 print:bg-indigo-100 text-indigo-300 print:text-indigo-900 border border-indigo-500/30'
                                          }`}
                                        >
                                          {item.priority}
                                        </span>
                                      </td>
                                      <td className="p-3 font-semibold text-white print:text-black">{item.initiative}</td>
                                      <td className="p-3 text-gray-300 print:text-gray-800">{item.impact}</td>
                                    </tr>
                                  ))}
                                </tbody>
                              </table>
                            </div>
                          </div>
                        )}
                      </div>
                    );
                  } catch (e) {
                    return <p className="text-sm text-gray-400">{selectedReport.contentJson}</p>;
                  }
                })()}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
