'use client';

import { useEffect, useState } from 'react';

type Report = {
  id: string;
  title: string;
  periodStart: string;
  periodEnd: string;
  generatedBy: string;
  createdAt: string;
  contentJson: string;
};

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [title, setTitle] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);

  useEffect(() => {
    load();
  }, []);

  async function load() {
    setLoading(true);
    try {
      const res = await fetch('/api/reports');
      if (res.ok) {
        const data: Report[] = await res.json();
        setReports(data);
        if (data.length > 0 && !selectedReport) {
          setSelectedReport(data[0]);
        }
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  }

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    if (!title.trim()) return;
    setGenerating(true);

    try {
      const res = await fetch('/api/reports', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title }),
      });

      if (res.ok) {
        setTitle('');
        setShowForm(false);
        await load();
      }
    } catch (e) {
      console.error(e);
    } finally {
      setGenerating(false);
    }
  }

  function handlePrint() {
    window.print();
  }

  function handleExportCSV() {
    if (!selectedReport) return;
    let data: any = {};
    try {
      data = JSON.parse(selectedReport.contentJson);
    } catch (e) {
      data = {};
    }

    const rows = [
      ['Report Property', 'Value'],
      ['Report Title', selectedReport.title],
      ['Generated By', selectedReport.generatedBy],
      ['Generated Date', new Date(selectedReport.createdAt).toLocaleString()],
      ['Executive Summary', `"${(data.summary || '').replace(/"/g, '""')}"`],
      ['Total Analyzed Feedbacks', data.totalAnalyzed || 0],
      ['Customer Satisfaction Score (CSAT)', `${data.csatScore || Math.round((data.positiveRatio || 0.7) * 100)}%`],
      ['Net Promoter Score (NPS Index)', data.npsIndex || 0],
      ['Positive Feedback Count', data.positiveCount || 0],
      ['Neutral Feedback Count', data.neutralCount || 0],
      ['Negative Feedback Count', data.negativeCount || 0],
      ['Support Tickets Count', data.channelBreakdown?.supportTickets || 0],
      ['App Store Reviews Count', data.channelBreakdown?.appStoreReviews || 0],
      ['NPS Surveys Count', data.channelBreakdown?.npsSurveys || 0],
      ['Sales Calls Count', data.channelBreakdown?.salesCalls || 0],
      ['Community Posts Count', data.channelBreakdown?.communityPosts || 0],
      ['Top Theme Clusters', `"${(data.topThemes || []).join(', ')}"`],
      ['Critical Pain Points', `"${(data.criticalPainPoints || []).join(' | ')}"`],
      ['Key Action Items', `"${(data.keyActionItems || []).join(' | ')}"`],
    ];

    if (Array.isArray(data.strategicRoadmap)) {
      rows.push(['Strategic Roadmap', '']);
      data.strategicRoadmap.forEach((item: any) => {
        rows.push([`[${item.priority}] ${item.initiative}`, `Impact: ${item.impact}`]);
      });
    }

    const csvContent = 'data:text/csv;charset=utf-8,' + rows.map((e) => e.join(',')).join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute(
      'download',
      `${selectedReport.title.replace(/\s+/g, '-').toLowerCase()}-${new Date(selectedReport.createdAt).toISOString().slice(0, 10)}.csv`
    );
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  function handleExportJSON() {
    if (!selectedReport) return;
    const blob = new Blob([selectedReport.contentJson], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${selectedReport.title.replace(/\s+/g, '-').toLowerCase()}-${new Date(selectedReport.createdAt).toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="p-6 md:p-8 max-w-7xl mx-auto w-full space-y-8 animate-fadeIn">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-white/10 pb-6 print:hidden">
        <div>
          <h1 className="text-2xl md:text-3xl font-extrabold text-white tracking-tight flex items-center gap-2">
            <span>Executive Feedback Reports</span>
          </h1>
          <p className="text-gray-400 text-sm mt-1">
            In-depth AI intelligence reports summarizing sentiment metrics, channel distributions, critical pain points, and C-suite roadmaps.
          </p>
        </div>
        <button
          onClick={() => setShowForm(!showForm)}
          className="px-4 py-2.5 rounded-xl text-sm font-semibold bg-gradient-to-r from-indigo-500 to-purple-600 hover:opacity-90 text-white shadow-md shadow-indigo-500/20 transition-all cursor-pointer"
        >
          {showForm ? '✕ Close Form' : '✨ Generate AI Report'}
        </button>
      </div>

      {/* Generate Report Form */}
      {showForm && (
        <form onSubmit={handleGenerate} className="glass-panel p-6 space-y-4 border-indigo-500/40 animate-fadeIn print:hidden">
          <h3 className="text-base font-bold text-white">Generate Executive Summary</h3>
          <div>
            <label className="text-xs font-semibold text-gray-400 block mb-1">Report Title</label>
            <input
              type="text"
              placeholder="e.g. Q3 Comprehensive Customer Feedback Intelligence Report"
              className="glass-input w-full text-sm"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
            />
          </div>
          <div className="flex justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={() => setShowForm(false)}
              className="px-4 py-2 rounded-lg text-sm text-gray-400 hover:text-white"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={generating}
              className="px-5 py-2 rounded-lg text-sm font-semibold bg-indigo-600 hover:bg-indigo-500 text-white shadow-md shadow-indigo-500/20 disabled:opacity-50 cursor-pointer"
            >
              {generating ? 'Synthesizing Detailed Report...' : 'Generate Report'}
            </button>
          </div>
        </form>
      )}

      {/* Reports Split Layout */}
      {loading ? (
        <div className="text-center py-12 text-gray-400 text-sm">Loading executive reports...</div>
      ) : reports.length === 0 ? (
        <div className="glass-panel p-12 text-center text-gray-400 text-sm">
          No reports generated yet. Click &quot;Generate AI Report&quot; to synthesize your first comprehensive summary.
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Left Column: Report History List */}
          <div className="space-y-3 print:hidden">
            <h3 className="text-sm font-bold uppercase tracking-wider text-gray-400 px-1">Generated Reports</h3>
            {reports.map((report) => {
              const isSelected = selectedReport?.id === report.id;
              return (
                <button
                  key={report.id}
                  onClick={() => setSelectedReport(report)}
                  className={`w-full text-left p-4 rounded-xl transition-all border cursor-pointer ${
                    isSelected
                      ? 'bg-indigo-600/20 border-indigo-500/50 shadow-md shadow-indigo-500/10'
                      : 'glass-panel hover:border-white/20'
                  }`}
                >
                  <h4 className="text-sm font-bold text-white mb-1 line-clamp-1">{report.title}</h4>
                  <div className="flex items-center justify-between text-xs text-gray-400">
                    <span>By {report.generatedBy}</span>
                    <span className="font-mono">{new Date(report.createdAt).toLocaleDateString()}</span>
                  </div>
                </button>
              );
            })}
          </div>

          {/* Right Column: Selected Report Detailed Preview & Exports */}
          <div className="lg:col-span-2">
            {selectedReport && (
              <div className="glass-panel p-8 space-y-8 border-indigo-500/30 print:p-0 print:border-none print:shadow-none">
                {/* Report Header & Action Buttons */}
                <div className="border-b border-white/10 pb-6 flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                  <div>
                    <h2 className="text-2xl font-extrabold text-white">{selectedReport.title}</h2>
                    <p className="text-xs text-gray-400 mt-1">
                      Generated by <strong className="text-indigo-300">{selectedReport.generatedBy}</strong> on{' '}
                      {new Date(selectedReport.createdAt).toLocaleString()}
                    </p>
                  </div>
                  <div className="flex flex-wrap items-center gap-2 print:hidden">
                    <button
                      onClick={handlePrint}
                      className="px-3 py-1.5 rounded-lg text-xs font-semibold bg-white/10 hover:bg-white/20 text-white border border-white/10 transition-all flex items-center gap-1 cursor-pointer"
                    >
                      <span>🖨️</span>
                      <span>Export PDF / Print</span>
                    </button>
                    <button
                      onClick={handleExportCSV}
                      className="px-3 py-1.5 rounded-lg text-xs font-semibold bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-300 border border-emerald-500/30 transition-all flex items-center gap-1 cursor-pointer"
                    >
                      <span>📊</span>
                      <span>Export CSV</span>
                    </button>
                    <button
                      onClick={handleExportJSON}
                      className="px-3 py-1.5 rounded-lg text-xs font-semibold bg-purple-500/20 hover:bg-purple-500/30 text-purple-300 border border-purple-500/30 transition-all flex items-center gap-1 cursor-pointer"
                    >
                      <span>⚙️</span>
                      <span>Export JSON</span>
                    </button>
                  </div>
                </div>

                {/* Parsed Detailed Content */}
                {(() => {
                  try {
                    const data = JSON.parse(selectedReport.contentJson);
                    const csat = data.csatScore || Math.round((data.positiveRatio || 0.7) * 100);
                    const nps = data.npsIndex || 0;
                    const cb = data.channelBreakdown || {};

                    return (
                      <div className="space-y-8 text-sm text-gray-200">
                        {/* Executive Summary */}
                        <div>
                          <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-400 mb-2">Executive Synthesis</h3>
                          <p className="p-5 rounded-xl bg-slate-900/90 border border-white/10 leading-relaxed text-sm text-gray-100">
                            {data.summary}
                          </p>
                        </div>

                        {/* Metrics Cards Grid */}
                        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                          <div className="p-4 rounded-xl bg-slate-900/80 border border-white/10">
                            <span className="text-xs text-gray-400 block">Total Analyzed</span>
                            <span className="text-2xl font-extrabold text-white mt-1 block">{data.totalAnalyzed || 0}</span>
                          </div>
                          <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/20">
                            <span className="text-xs text-emerald-400 block">CSAT Satisfaction Score</span>
                            <span className="text-2xl font-extrabold text-emerald-300 mt-1 block">{csat}%</span>
                          </div>
                          <div className="p-4 rounded-xl bg-indigo-500/10 border border-indigo-500/20">
                            <span className="text-xs text-indigo-400 block">Net Promoter Index</span>
                            <span className="text-2xl font-extrabold text-indigo-300 mt-1 block">+{nps}</span>
                          </div>
                          <div className="p-4 rounded-xl bg-purple-500/10 border border-purple-500/20">
                            <span className="text-xs text-purple-400 block">Positive Ratio</span>
                            <span className="text-2xl font-extrabold text-purple-300 mt-1 block">
                              {((data.positiveRatio || 0) * 100).toFixed(0)}%
                            </span>
                          </div>
                        </div>

                        {/* Sentiment Counts & Channel Distribution */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                          <div className="p-5 rounded-xl bg-slate-900/80 border border-white/10 space-y-3">
                            <h4 className="text-xs font-bold uppercase tracking-wider text-gray-400">Sentiment Distribution</h4>
                            <div className="space-y-2 text-xs">
                              <div className="flex items-center justify-between">
                                <span className="text-emerald-400 font-medium">Positive Feedbacks</span>
                                <span className="font-bold">{data.positiveCount || 0}</span>
                              </div>
                              <div className="flex items-center justify-between">
                                <span className="text-amber-400 font-medium">Neutral Feedbacks</span>
                                <span className="font-bold">{data.neutralCount || 0}</span>
                              </div>
                              <div className="flex items-center justify-between">
                                <span className="text-rose-400 font-medium">Negative Feedbacks</span>
                                <span className="font-bold">{data.negativeCount || 0}</span>
                              </div>
                            </div>
                          </div>

                          <div className="p-5 rounded-xl bg-slate-900/80 border border-white/10 space-y-3">
                            <h4 className="text-xs font-bold uppercase tracking-wider text-gray-400">Channel Volume Breakdown</h4>
                            <div className="grid grid-cols-2 gap-2 text-xs">
                              <div className="p-2 rounded bg-white/5 flex justify-between">
                                <span className="text-gray-400">Support Tickets:</span>
                                <span className="font-bold text-white">{cb.supportTickets || 0}</span>
                              </div>
                              <div className="p-2 rounded bg-white/5 flex justify-between">
                                <span className="text-gray-400">App Store:</span>
                                <span className="font-bold text-white">{cb.appStoreReviews || 0}</span>
                              </div>
                              <div className="p-2 rounded bg-white/5 flex justify-between">
                                <span className="text-gray-400">NPS Surveys:</span>
                                <span className="font-bold text-white">{cb.npsSurveys || 0}</span>
                              </div>
                              <div className="p-2 rounded bg-white/5 flex justify-between">
                                <span className="text-gray-400">Sales Calls:</span>
                                <span className="font-bold text-white">{cb.salesCalls || 0}</span>
                              </div>
                            </div>
                          </div>
                        </div>

                        {/* Top Themes */}
                        {data.topThemes && (
                          <div>
                            <h3 className="text-xs font-bold uppercase tracking-wider text-purple-400 mb-3">Top Theme Clusters</h3>
                            <div className="flex flex-wrap gap-2">
                              {data.topThemes.map((t: string, idx: number) => (
                                <span key={idx} className="px-3.5 py-1.5 rounded-lg bg-purple-500/20 text-purple-300 border border-purple-500/30 text-xs font-semibold">
                                  #{idx + 1} {t}
                                </span>
                              ))}
                            </div>
                          </div>
                        )}

                        {/* Critical Pain Points & Churn Risks */}
                        {data.criticalPainPoints && (
                          <div>
                            <h3 className="text-xs font-bold uppercase tracking-wider text-rose-400 mb-3 flex items-center gap-1.5">
                              <span>⚠️ Critical Pain Points & Churn Risks</span>
                            </h3>
                            <div className="space-y-2">
                              {data.criticalPainPoints.map((point: string, idx: number) => (
                                <div key={idx} className="p-3.5 rounded-xl bg-rose-500/10 border border-rose-500/20 text-xs text-rose-200 flex items-start gap-2">
                                  <span className="font-bold text-rose-400">🚨</span>
                                  <span>{point}</span>
                                </div>
                              ))}
                            </div>
                          </div>
                        )}

                        {/* Recommended Action Items */}
                        {data.keyActionItems && (
                          <div>
                            <h3 className="text-xs font-bold uppercase tracking-wider text-amber-400 mb-3">Tactical Action Items</h3>
                            <ul className="space-y-2">
                              {data.keyActionItems.map((item: string, idx: number) => (
                                <li key={idx} className="p-3.5 rounded-xl bg-slate-900/90 border border-white/10 flex items-start gap-3 text-xs">
                                  <span className="px-2 py-0.5 rounded bg-amber-500/20 text-amber-300 font-bold text-[10px]">STEP {idx + 1}</span>
                                  <span className="text-gray-200">{item}</span>
                                </li>
                              ))}
                            </ul>
                          </div>
                        )}

                        {/* Strategic C-Suite Roadmap */}
                        {data.strategicRoadmap && (
                          <div>
                            <h3 className="text-xs font-bold uppercase tracking-wider text-cyan-400 mb-3">Strategic C-Suite Roadmap</h3>
                            <div className="overflow-x-auto rounded-xl border border-white/10">
                              <table className="w-full text-left text-xs">
                                <thead className="bg-slate-900/90 text-gray-400 font-semibold border-b border-white/10">
                                  <tr>
                                    <th className="p-3">Priority</th>
                                    <th className="p-3">Initiative</th>
                                    <th className="p-3">Target Impact</th>
                                  </tr>
                                </thead>
                                <tbody className="divide-y divide-white/5">
                                  {data.strategicRoadmap.map((item: any, idx: number) => (
                                    <tr key={idx} className="hover:bg-white/5">
                                      <td className="p-3">
                                        <span className={`px-2 py-0.5 rounded font-bold text-[10px] ${
                                          item.priority === 'HIGH' ? 'bg-rose-500/20 text-rose-300 border border-rose-500/30' :
                                          item.priority === 'MEDIUM' ? 'bg-amber-500/20 text-amber-300 border border-amber-500/30' :
                                          'bg-indigo-500/20 text-indigo-300 border border-indigo-500/30'
                                        }`}>
                                          {item.priority}
                                        </span>
                                      </td>
                                      <td className="p-3 font-semibold text-white">{item.initiative}</td>
                                      <td className="p-3 text-gray-300">{item.impact}</td>
                                    </tr>
                                  ))}
                                </tbody>
                              </table>
                            </div>
                          </div>
                        )}
                      </div>
                    );
                  } catch (e) {
                    return <p className="text-sm text-gray-400">{selectedReport.contentJson}</p>;
                  }
                })()}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
