export type DemoFeedback = {
  id: string;
  content: string;
  channel: string;
  sourceRef: string;
  customerLabel: string;
  sentiment: 'POS' | 'NEU' | 'NEG';
  sentimentScore: number;
  status: string;
  createdAt: string;
  themes: { theme: { id: string; name: string; color: string } }[];
};

export const DEMO_FEEDBACKS: DemoFeedback[] = [
  {
    id: 'demo-fb-1',
    content: 'The dashboard load time has improved dramatically after the latest update! Really crisp animations and responsive charts.',
    channel: 'app_store',
    sourceRef: 'AppStore #9421',
    customerLabel: 'Enterprise Client - TechFlow',
    sentiment: 'POS',
    sentimentScore: 0.94,
    status: 'ACTIONED',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    themes: [{ theme: { id: 'th-1', name: 'Performance & Speed', color: '#3B82F6' } }],
  },
  {
    id: 'demo-fb-2',
    content: 'We need automated weekly PDF export reports so our executive team can review feedback without logging in every day.',
    channel: 'sales_call',
    sourceRef: 'Zoom Call 2026-08-02',
    customerLabel: 'VP Product - InnovateHQ',
    sentiment: 'NEU',
    sentimentScore: 0.55,
    status: 'NEW',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    themes: [{ theme: { id: 'th-5', name: 'Feature Requests', color: '#EC4899' } }],
  },
  {
    id: 'demo-fb-3',
    content: 'Billing invoice failed to generate the tax breakdown item. Customer support took 3 days to reply to our ticket.',
    channel: 'support_ticket',
    sourceRef: 'Ticket #4812',
    customerLabel: 'Finance Director - Apex Global',
    sentiment: 'NEG',
    sentimentScore: 0.12,
    status: 'NEW',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    themes: [{ theme: { id: 'th-3', name: 'Billing & Subscriptions', color: '#10B981' } }],
  },
  {
    id: 'demo-fb-4',
    content: 'The Slack integration setup was seamless! We get real-time alerts whenever a customer leaves an NPS rating < 6.',
    channel: 'community_post',
    sourceRef: 'Discord #integrations',
    customerLabel: 'Community Lead',
    sentiment: 'POS',
    sentimentScore: 0.91,
    status: 'REVIEWED',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    themes: [{ theme: { id: 'th-4', name: 'Integrations & Webhooks', color: '#F59E0B' } }],
  },
  {
    id: 'demo-fb-5',
    content: 'Mobile menu dropdown gets cut off on smaller iPhone screens in dark mode.',
    channel: 'app_store',
    sourceRef: 'AppStore #8801',
    customerLabel: 'Mobile User',
    sentiment: 'NEG',
    sentimentScore: 0.28,
    status: 'REVIEWED',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    themes: [{ theme: { id: 'th-2', name: 'UI/UX Usability', color: '#8B5CF6' } }],
  },
  {
    id: 'demo-fb-6',
    content: 'Our account was double-charged this month and the refund process has been a nightmare to get through.',
    channel: 'support_ticket',
    sourceRef: 'Ticket #5247',
    customerLabel: 'Ops Lead - Northwind',
    sentiment: 'NEG',
    sentimentScore: 0.08,
    status: 'REVIEWED',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    themes: [{ theme: { id: 'th-3', name: 'Billing & Subscriptions', color: '#10B981' } }],
  },
  {
    id: 'demo-fb-7',
    content: 'I have been waiting 5 days for a response on our priority ticket. This is unacceptable for an enterprise plan.',
    channel: 'support_ticket',
    sourceRef: 'Ticket #5310',
    customerLabel: 'IT Director - TechFlow',
    sentiment: 'NEG',
    sentimentScore: 0.09,
    status: 'NEW',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    themes: [{ theme: { id: 'th-4', name: 'Integrations & Webhooks', color: '#F59E0B' } }],
  },
  {
    id: 'demo-fb-8',
    content: 'The latest iOS update makes the app freeze when scrolling through long feedback lists.',
    channel: 'app_store',
    sourceRef: 'AppStore #9032',
    customerLabel: 'Mobile Reviewer',
    sentiment: 'NEG',
    sentimentScore: 0.17,
    status: 'REVIEWED',
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    themes: [{ theme: { id: 'th-1', name: 'Performance & Speed', color: '#3B82F6' } }],
  },
  {
    id: 'demo-fb-9',
    content: 'Overall NPS rating 9/10. The AI auto-tagging feature saves our team over 5 hours every week during sprint reviews.',
    channel: 'nps_survey',
    sourceRef: 'NPS Q3 Survey',
    customerLabel: 'Growth Lead - SaaSify',
    sentiment: 'POS',
    sentimentScore: 0.96,
    status: 'ACTIONED',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    themes: [{ theme: { id: 'th-5', name: 'Feature Requests', color: '#EC4899' } }],
  },
  {
    id: 'demo-fb-10',
    content: 'NPS 4. The platform has been extremely slow since last week, frustrating our whole team during reviews.',
    channel: 'nps_survey',
    sourceRef: 'NPS Q3 Survey',
    customerLabel: 'Team Lead - CloudNine',
    sentiment: 'NEG',
    sentimentScore: 0.13,
    status: 'REVIEWED',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    themes: [{ theme: { id: 'th-1', name: 'Performance & Speed', color: '#3B82F6' } }],
  },
  {
    id: 'demo-fb-11',
    content: 'Exporting large CSV files with 50,000+ rows times out occasionally during peak hours.',
    channel: 'support_ticket',
    sourceRef: 'Ticket #5092',
    customerLabel: 'Data Ops Manager',
    sentiment: 'NEG',
    sentimentScore: 0.21,
    status: 'NEW',
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    themes: [{ theme: { id: 'th-1', name: 'Performance & Speed', color: '#3B82F6' } }],
  },
  {
    id: 'demo-fb-12',
    content: 'NPS 2. Billing errors and unexpected charges are pushing us to cancel our subscription.',
    channel: 'nps_survey',
    sourceRef: 'NPS Q3 Survey',
    customerLabel: 'CEO - StartupLab',
    sentiment: 'NEG',
    sentimentScore: 0.04,
    status: 'NEW',
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    themes: [{ theme: { id: 'th-3', name: 'Billing & Subscriptions', color: '#10B981' } }],
  },
  {
    id: 'demo-fb-13',
    content: 'Still waiting for bulk PDF export. Our team exports individual reports all day which is painful.',
    channel: 'community_post',
    sourceRef: 'Forum #feature-requests',
    customerLabel: 'Ops Analyst',
    sentiment: 'NEG',
    sentimentScore: 0.29,
    status: 'REVIEWED',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    themes: [{ theme: { id: 'th-5', name: 'Feature Requests', color: '#EC4899' } }],
  },
  {
    id: 'demo-fb-14',
    content: 'The HubSpot integration during the demo was impressive and would solve our sync pain points right away.',
    channel: 'sales_call',
    sourceRef: 'Demo Call 2026-08-05',
    customerLabel: 'RevOps Lead - InnovateHQ',
    sentiment: 'POS',
    sentimentScore: 0.89,
    status: 'REVIEWED',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    themes: [{ theme: { id: 'th-4', name: 'Integrations & Webhooks', color: '#F59E0B' } }],
  },
];